package co.romulo.doctorWhoGuide.Episodes.activities;

import android.content.Context;
import co.romulo.doctorWhoGuide.Episodes.Models.Episode;
import co.romulo.doctorWhoGuide.Episodes.adapters.EpisodeArrayAdapter;
import dagger.Module;
import dagger.Provides;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;

@Module(injects = EpisodeListActivity.class)
public class EpisodeArrayAdapterProvider {
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    Episode[] episodes;
    private Context context;
    private int resource;


    public EpisodeArrayAdapterProvider(Context context, int resource) {
        this.context = context;
        this.resource = resource;
        try {
            episodes = new Episode[]{
                    //season 1
                    new Episode(1, 1, 1, "Rose", "Rose Tyler is just an ordinary shop worker living an ordinary life in 21st century Britain. But that life is turned upside down when a strange man calling himself The Doctor drags her into an alien invasion attempt!", sdf.parse("17-03-2006")),
                    new Episode(2, 1, 2, "The End of the World", "Rose goes off on her first adventure with the Doctor who takes her 5 billion years into the future to view a cataclysmic event: the destruction of the Earth. They're on an orbiting space platform with a groups of invited guests who seem to travel from one cataclysmic event to another. There are uninvited guests as well in the form of spider-like mechanical robots that seem to multiply at will and are obviously bent on causing destruction. The spiders soon dispose of the Steward and gain control of the orbiting platform's mainframe. It doesn't take long for the Doctor ...", sdf.parse("17-03-2006")),
                    new Episode(3, 1, 3, "The Unquiet Dead", "The Doctor has great expectations for his latest adventure when he and Rose join forces with Charles Dickens to investigate a mysterious plague of zombies.", sdf.parse("24-03-2006")),
                    new Episode(4, 1, 4, "Aliens of London", "The Doctor returns Rose to her own time - well, sort of - but her family reunion is ruined when a spaceship crashes in the middle of London. What is the origin of the spaceship, and where has the Prime Minister gone in this time of crisis?", sdf.parse("31-03-2006")),
                    new Episode(5, 1, 5, "World War Three", "The fiendish Slitheen have been unmasked as the ones who crashed the spaceship into London as part of a ruse to trigger World War Three. But how can The Doctor save the planet when he's trapped inside a locked room?", sdf.parse("07-04-2006")),
                    new Episode(6, 1, 6, "Dalek", "The Doctor and Rose travel to the year 2012 and land in a museum of extra-terrestrial objects accumulated by the very wealthy Henry van Statten. He's an avid collector - the TARDIS lands on the museum's 53rd floor below ground level - but he's also using alien technology to develop new weapons from which he derives his large income. He's particularly proud of one device he's acquired but has not yet been able to make functional and to the Doctor's horror, it turns out to a very old and very dangerous enemy from the past.", sdf.parse("14-04-2006")),
                    new Episode(7, 1, 7, "The Long Game", "The Doctor and Rose arrive in the year 200,000 to see The Fourth Great and Bountiful Human Empire. But something has gone wrong - someone is holding back the development of mankind. Who could have done this? And why?", sdf.parse("21-04-2006")),
                    new Episode(8, 1, 8, "Father's Day", "All of her life, Rose's mother told how great a man her father Pete was. He was killed by a hit and run driver when Rose was just a baby and among her many regrets was that her father died alone, just lying on the street. Rose asks the Doctor to take her back to that day. Rather than just be with him when he dies, she actually saves him and later admits that this was her plan all along. She soon realizes that her parents' marriage was not exactly the golden relationship she had claimed it to be. Far worse however, is that by saving her father, Rose has created a tear ...", sdf.parse("28-04-2006")),
                    new Episode(9, 1, 9, "The Empty Child", "Rose and the Doctor find themselves in 1941 London when the TARDIS receives an emergency signal from another time-traveling vehicle. While the Doctor tries to determine where the object may have landed, Rose goes off in search of a child she can hear calling for help. When she gets herself into a precarious situation, she's rescued by the rather handsome RAF Captain Jack Harkness, who owns a time machine of his own. The Doctor meanwhile meets Nancy who has an interesting way of arranging meals for homeless children. They are also being chased by the child Rose heard ...", sdf.parse("05-05-2006")),
                    new Episode(10, 1, 10, "The Doctor Dances", "The Doctor, Rose and Captain Jack Harkness are still in the hospital with the gas mask-wearing mutants and are having some trouble finding a way out. The Doctor determines that the ambulance Captain Jack was using in his scam contained nano genes, similar to the one's he used to repair Rose's rope-burned hands. Only in this case, there are enough nano genes on the loose to \"repair\" an entire species and they have no idea what a human looks like in the first place. The future of the human race lies in Nancy accepting her true relationship to the little boy who is ...", sdf.parse("12-05-2006")),
                    new Episode(11, 1, 11, "Boom Town", "Stopping off in present-day Cardiff to recharge the TARDIS, The Doctor, Rose and Jack encounter an old foe in the midst of hatching a scheme that could destroy the entire planet.", sdf.parse("19-05-2006")),
                    new Episode(12, 1, 12, "Bad Wolf", "Jack, The Doctor and Rose have been kidnapped and forced to play terrible and deadly games. But what happens to the bodies of the murdered contestants? And what sinister plot do the games hide?", sdf.parse("02-06-2006")),
                    new Episode(13, 1, 13, "The Parting of the Ways", "The Dalek fleet is poised to destroy the Earth and only The Doctor, Rose, Jack and a band of television producers can stop them.", sdf.parse("09-06-2006")),
                    //season 2
                    new Episode(14, 2, 1, "The Christmas Invasion", "It's Christmas Eve, but this is to be a far from silent night - the cruel Sycorax have come to Earth to enslave mankind and, as ever, only The Doctor can stop them. Unfortunately, he's lying in a coma in Jackie's home...", sdf.parse("29-09-2006")),
                    new Episode(15, 2, 2, "New Earth", "As Rose Tyler embarks upon her first big TARDIS adventure with the newly-regenerated Doctor, they discover a sinister hospital run by strange cat people and run in to two old acquaintances, The Face of Boe and Cassandra.", sdf.parse("29-09-2006")),
                    new Episode(16, 2, 3, "Tooth and Claw", "The Doctor and Rose are transported to 19th Century Scotland, where they meet Queen Victoria, and try to protect her from a ravenous werewolf and a band of assassinating warrior-monks", sdf.parse("06-10-2006")),
                    new Episode(17, 2, 4, "School Reunion", "The Krillitanes - aliens with a mix-and-match physiology - are trying to crack the 'God-Maker', a paradigm to give them ultimate power. They are using children as a computer, and only the Doctor and Rose, re-united with Sarah Jane Smith and K9 can prevent them from becoming masters of time and space.", sdf.parse("13-10-2006")),
                    new Episode(18, 2, 5, "The Girl in the Fireplace", "The Doctor, Mickey and Rose land on a spaceship in the 51st century only to find 18th century Versailles on board, the time of Madame De Pompadour! To find out what's going on the Doctor must enter Versailles and save Madame De Popmpadour but it turns into an emotional roller coaster for the Doctor.", sdf.parse("20-10-2006")),
                    new Episode(19, 2, 6, "Rise of the Cybermen", "Upon landing on an alternate version of the Earth, The Doctor, Rose and Mickey learn that Peter Tyler is apparently alive and well. Lurking in the shadows are creatures made to destroy - one of The Doctor's greatest fears have come true...the Cybermen are reborn.", sdf.parse("27-10-2006")),
                    new Episode(20, 2, 7, "The Age of Steel", "Lumic's army of cybermen is on the rise, and with more and more people being converted by the hour, time is of the essence. The gang are reduced to fugitives as they roam the streets of parallel London trying to rid the earth of cybermen.", sdf.parse("03-11-2006")),
                    new Episode(21, 2, 8, "The Idiot's Lantern", "In 1950s London, the police are hunting down strange, mute creatures. The people of Britain gather around their new-fangled \"tele-vision\" sets to celebrate the new Queen's coronation - but is something affecting the signal?", sdf.parse("10-11-2006")),
                    new Episode(22, 2, 9, "The Impossible Planet", "The TARDIS lands on an alien planet shrouded in a darkness that even the Doctor can't figure out. And what is lurking at the bottom of The Satan Pit?", sdf.parse("17-11-2006")),
                    new Episode(23, 2, 10, "The Satan Pit", "As Rose battles the murderous Ood, the Doctor finds his every belief being challenged to the core, as the Pit beckons. With the planet threatening to fall into the black hole, the Doctor must make the ultimate sacrifice.", sdf.parse("01-12-2006")),
                    new Episode(24, 2, 11, "Love & Monsters", "A run in with the Doctor at a young age leads Elton to a group who's studying him, they become friends and have a laugh until Victor Kennedy arrives. Suddenly everything becomes more serious then people start disappearing from the group. Can the Doctor save Elton and explain his past before he's absorbed by the Absorbaloff", sdf.parse("08-12-2006")),
                    new Episode(25, 2, 12, "Fear Her", "The Doctor and Rose travel to London in 2012 to see the Olympics - only to find that children are mysteriously disappearing before peoples very eyes. The answer seems to lie with a young girl named Chloe and her strange drawings - but is there something more sinister behind the disappearances?", sdf.parse("15-12-2006")),
                    new Episode(26, 2, 13, "Army of Ghosts", "As the ghosts of loved ones appear, the whole world celebrates. But as the Doctor investigates he believes that there is a more sinister motive behind their appearence. And deep within the Torchwood tower, a mysterious sphere containing the greatest enemies of the Doctor is opened...", sdf.parse("22-11-2006")),
                    new Episode(27, 2, 14, "Doomsday", "Earth becomes the battlefield for the greatest and deadliest war of all time, as the Daleks and the Cybermen clash with the whole universe at stake. The Doctor and Rose, reunited with old friends and Cybermen experts Mickey and Jake, race to find a way to bring the war to an end before it brings about the destruction of the whole of space and time. But the Doctor soon faces an even bigger dilemma - could ending the war mean the death of Rose?", sdf.parse("22-12-2006")),
                    //season 3
                    new Episode(28, 3, 1, "The Runaway Bride", "A young bride in the midst of her wedding finds herself mysteriously transported to the TARDIS. The Doctor must discover what her connection is with the Empress of Racnoss's plan to destroy the world.", sdf.parse("06-07-2007")),
                    new Episode(29, 3, 2, "Smith and Jones", "When the hospital where medical student Martha Jones works at is transported to the moon, only the Doctor can come to the rescue and face the might of the Judoon.", sdf.parse("06-07-2007")),
                    new Episode(30, 3, 3, "The Shakespeare Code", "The Doctor takes Martha to 1599, to meet none other than William Shakespeare in the Globe Theatre...but can he stop the curse of the three witches?", sdf.parse("07-04-2007")),
                    new Episode(31, 3, 4, "Gridlock", "The Doctor and Martha go back to New Earth were The Doctor will encounter the Face of Boe who will tell The Doctor \"The Great Secret\".", sdf.parse("14-04-2007")),
                    new Episode(32, 3, 5, "Daleks in Manhattan", "The Doctor and Martha confront a host of surviving Daleks from the Canary Wharf battle. What are those creatures in the sewers? Who is Solomon? And why are the Cult Of Skaro attempting to create a Dalek/Human hybrid...?", sdf.parse("21-04-2007")),
                    new Episode(33, 3, 6, "Evolution of the Daleks", "Concluding part to Daleks in Manhattan. In 1930s New York, the Daleks' plan is in full force. Faced with the cyborgs' most evil and dangerous scheme yet, will the Doctor and Martha be able to defeat their greatest opponents?", sdf.parse("28-04-2007")),
                    new Episode(34, 3, 7, "The Lazarus Experiment", "The famous Dr Lazarus has appeared to discover the secret of eternal youth - but do his experiments hide a sinister secret?", sdf.parse("05-05-2007")),
                    new Episode(35, 3, 8, "42", "On a spaceship headed straight for the center of the sun, The Doctor only has 42 minutes to save Martha and the rest of the ship's crew from an inevitable doom...", sdf.parse("19-05-2007")),
                    new Episode(36, 3, 9, "Human Nature", "In 1913, Martha watches in jealousy from afar as The Doctor learns what it is to be human and to fall in love with the local school nurse, Joan Redfern.", sdf.parse("26-05-2007")),
                    new Episode(37, 3, 10, "The Family of Blood", "The Doctor must deal with the repercussions of his decision to become human, as The Family Of Blood unveil themselves...", sdf.parse("02-06-2007")),
                    new Episode(38, 3, 11, "Blink", "\"Don't Blink. Blink and you're dead. Don't turn your back. Don't look away. And don't Blink. Good Luck.\" These cryptic messages left on 17 DVD\'s leave Sally Sparrow on a journey to assist the Doctor and Martha Jones, who are trapped in 1969. But Sally is in 2007, and they won't meet until 2008. Strange? Unusual? Not if you are the Doctor.", sdf.parse("09-06-2007")),
                    new Episode(39, 3, 12, "Utopia", "Soon after bumping into old friend Jack Harkness, Martha and The Doctor head off to Malcassairo, a distant planet where an old professor will do anything he can to keep his people alive...", sdf.parse("16-06-2007")),
                    new Episode(40, 3, 13, "The Sound of Drums", "The Doctor, Martha and Jack return to the 21st Century eighteen months after the Doctor and Martha left. They find they've missed the election, and the new Prime Minister, Harold Saxon, is someone they've met before by another name.", sdf.parse("23-06-2007")),
                    new Episode(41, 3, 14, "Last of the Time Lords", "It's been a year since The Master unleashed the mysterious Toclafane onto Earth. With the human race and The Doctor enslaved under The Master's control, Martha Jones is the only person that can help stop the evil Time Lord.", sdf.parse("30-06-2007")),
                    //season 4
                    new Episode(42, 4, 1, "Voyage of the Damned", "The Doctor finds his TARDIS colliding with a spaceship based on the RMS Titanic during a Christmas party. With the help of a waitress named Astrid, the Doctor must take on the race called the Hosts as the lives of the Titanic crew and those on Earth are in danger.", sdf.parse("18-04-2008")),
                    new Episode(43, 4, 2, "Partners in Crime", "With a new weight-loss pill tested in London by Adipose Industries, The Doctor goes to investigate the sinister truth behind the product, only to find out that his old friend Donna Noble is investigating as well.", sdf.parse("25-04-2008")),
                    new Episode(44, 4, 3, "The Fires of Pompeii", "The Doctor and Donna visit Pompeii in AD 79, on the eve of the eruption of Mount Vesuvius.", sdf.parse("02-05-2008")),
                    new Episode(45, 4, 4, "Planet of the Ood", "Finding themselves on the Ood-Sphere planet in the 42nd century, The Doctor and Donna discover the truth over the Ood's willingness to serve humankind.", sdf.parse("09-05-2008")),
                    new Episode(46, 4, 5, "The Sontaran Stratagem", "UNIT's newest recruit Martha Jones enlists The Doctor's help to investigate kid genius Luke Rattigan and his ATMOS system that is used in every car on Earth.", sdf.parse("16-05-2008")),
                    new Episode(47, 4, 6, "The Poison Sky", "With planet Earth choking under the poison sky, the Doctor must stop the Sontarans' threat to the planet.", sdf.parse("30-05-2008")),
                    new Episode(48, 4, 7, "The Doctor's Daughter", "Caught in the middle of a war between the Humans and the Hath in the planet Messaline, the Doctor finds himself once again a father.", sdf.parse("06-06-2008")),
                    new Episode(49, 4, 8, "The Unicorn and the Wasp", "With a 1920s dinner party turning into a murder mystery, The Doctor and Donna meet Agatha Christie on the eve of her publicized disappearance.", sdf.parse("13-06-2008")),
                    new Episode(50, 4, 9, "Silence in the Library", "The Doctor and Donna join a group of archaeologists at a 51st century library. What caused the library to become abandoned? What are the Nodes? And what links the library to one little girl? All they have is one warning - count the shadows.", sdf.parse("20-06-2008")),
                    new Episode(51, 4, 10, "Forest of the Dead", "With the library darkening, the Doctor takes on the Vashta Nerada while figuring out what links River Song to his future. Meanwhile, Donna finds out the mystery of Dr. Moon and the Girl.", sdf.parse("27-06-2008")),
                    new Episode(52, 4, 11, "Midnight", "As part of a well-deserved holiday, the Doctor takes a bus tour on the planet Midnight. Little does he know that something is knocking on that bus' wall...", sdf.parse("11-07-2008")),
                    new Episode(53, 4, 12, "Turn Left", "What would happen if Donna never met the Doctor? How would Earth handle the Racnoss, the falling Titanic or the Sontarans? Aided by a familiar blonde time traveler, Donna corrects the alternate time line from happening.", sdf.parse("21-06-2008")),
                    new Episode(54, 4, 13, "The Stolen Earth", "The return of an old enemy leaves Earth along with 26 other planets stolen from their places. As the Doctor and Donna look for the whereabouts of Earth, former companions of the Doctor assemble a resistance against the new Dalek Empire.", sdf.parse("28-06-2008")),
                    new Episode(55, 4, 14, "Journey's End", "In the wake of Davros' threat to destroy the existence of the Universe itself, the Doctor's companions unite to stop the Dalek empire. Which one will die by the prophecies and what will the fate be for the Doctor?", sdf.parse("05-07-2008")),
                    //season 5
                    new Episode(56, 5, 1, "The Eleventh Hour", "With his TARDIS in ruins, the newly-regenerated Doctor with the help of Amy Pond must save the world in less than twenty minutes from galactic policemen known as the Atraxi.", sdf.parse("17-04-2010")),
                    new Episode(57, 5, 2, "The Beast Below", "The Doctor takes Amy to the future inside Starship UK, which contains in addition to British explorers, an intimidating race known as the Smilers.", sdf.parse("10-04-2010")),
                    new Episode(58, 5, 3, "Victory of the Daleks", "The TARDIS takes The Doctor and Amy to war-torn Britain in the middle of World War Two. Not only do they meet Winston Churchill himself, but the Doctor comes face to face once again with his greatest enemy of all.", sdf.parse("17-04-2010")),
                    new Episode(59, 5, 4, "The Time of Angels", "The Doctor and Amy emerge from the TARDIS to find the wreck of the Byzantium spaceship. Down below the Weeping Angels are stirring, but the Doctor has someone else to contend with; none other than the mysterious Professor River Song.", sdf.parse("24-04-2010")),
                    new Episode(60, 5, 5, "Flesh and Stone", "The Doctor, Amy, Dr. Song and the remaining soldiers manage to escape from the crashed ship and into the forest. The Angels attempt to create a rift in time and space much as the Doctor had found in Amy's room when they first met. Amy meanwhile is counting down from 10 minutes and the Doctor has determined that an Angel has taken over her mind.", sdf.parse("01-05-2010")),
                    new Episode(61, 5, 6, "The Vampires of Venice", "The Doctor and Amy cross swords in more ways than one with a horde of blood-sucking vampires in 16th century Venice.", sdf.parse("08-05-2010")),
                    new Episode(62, 5, 7, "Amy's Choice", "Five years after finally leaving the TARDIS Amy and Rory now married, live in the quiet little village of Leadworth. But everything is not what it would seem.", sdf.parse("15-05-2010")),
                    new Episode(63, 5, 8, "The Hungry Earth", "The Doctor tries to get everyone to Rio, but nothing quite goes as planned. They arrive in a small Welsh village where the Doctor immediately senses that the ground isn't quite right. There is a drilling rig nearby that has reached a depth of 21 kilometers when odd things begin to happen. A local village man has disappeared and soon after Amy is swallowed into the ground. The Doctor realizes that the drilling has disturbed an ancient reptilian race that has lived deep underground for thousands upon thousands of years and who are determined to protect themselves ...", sdf.parse("22-05-2010")),
                    new Episode(64, 5, 9, "Cold Blood", "The Doctor and Nasreen Chaudry go deep underground and find an ancient society that has been disturbed by the drilling. They are gassed and taken prisoner just as Amy manages to free herself. The military commander of the underground reptilians, Restac, is convinced that the \"apes' - their term for humans - are an invading force. Calmer heads prevail and the Doctor manages to negotiate a truce pending the transfer of prisoners which he, and some of the more pacifist members of the reptilians, hopes will lead to a lasting peace. The only problem is that Alaya, the ...", sdf.parse("29-05-2010")),
                    new Episode(65, 5, 10, "Vincent and the Doctor", "Visiting a museum, the Doctor and Amy are especially excited with the gallery for Vincent van Gogh. Many of van Gogh pieces are displayed, including \"The Church at Auvers (1890)\". However there is something irregular discovered on the painting - a small alien image within a window pane. The Doctor quickly takes Amy back to 1890 where they locate the troubled artist that upsets the locals, cannot pay his bills, and is able to see an invisible monster that no one else is able to see.", sdf.parse("05-06-2010")),
                    new Episode(66, 5, 11, "The Lodger", "No sooner does the TARDIS land on Earth that it leaves again - but without the Doctor who had just stepped outside. The Doctor soon finds himself at the home of Craig Owens, who has been advertising for a lodger. There's clearly something odd in the house with people being lured to the upstairs room, but never reappearing. The Doctor is having a good time of it and is having a bit of fun; he proves to be a rather good football player. Craig the landlord is very much in love with Sophie but can't quite bring himself to tell her. The Doctor tries to help them out. But ...", sdf.parse("10-07-2010")),
                    new Episode(67, 5, 12, "The Pandorica Opens", "River Song returns to deliver The Doctor a serious warning from his allies: the mythical Pandorica, said to contain the most feared creature in the entire Universe, is opening.", sdf.parse("17-07-2010")),
                    new Episode(68, 5, 13, "The Big Bang", "The Daleks, Cybermen and others have imprisoned in the Pandorica the most dangerous creature in the universe - the Doctor, who they say will in the future destroy the universe. Moving to 1996, a preteen Amy Pond visits a museum with her Aunt and opens the Pandorica, only to find the adult version of herself inside. Traveling back and forth in time, the Doctor tries to make sense of it all and find River Song, who is also missing. He realizes that there is only one explanation for a starless universe.", sdf.parse("26-06-2010")),
                    //season 6
                    new Episode(69, 6, 1, "A Christmas Carol", "A space liner, with a large number of passengers aboard, is in difficulties while flying through the atmosphere of an unknown planet. Amy and Rory have been spending some time on board in the honeymoon suite and they quickly appear on deck. Amy calls the doctor for help and the TARDIS soon appears ahead of the ship. However the Doctor cannot save them and the only other option is to land on the planet below. There the Doctor meets a Scrooge like figure by the name of Kazran Sardick, the only person that can save Amy, Rory and all the other lives on the Spacecraft. The...", sdf.parse("25-12-2010")),
                    new Episode(70, 6, 2, "The Impossible Astronaut", "River Song, Rory, The Doctor and Amy are reunited in the Utah desert", sdf.parse("23-04-2011")),
                    new Episode(71, 6, 3, "Day of the Moon", "Still in 1969, the Doctor has come to the conclusion that the alien creatures are only seen when they directly look at them. As soon as you look away, any memory of their presence is wiped clean. The aliens are also able to leave suggestions in people's minds, and aren't invaders per se, but have been on Earth for a very long time. While the Doctor works to ensure the success of Apollo 11, the others try to solve the mystery of the little girl in the space suit.", sdf.parse("30-04-2011")),
                    new Episode(72, 6, 4, "The Curse of the Black Spot", "On board a 17th century pirate ship sailing the ocean waves, a crew under the command of one Captain Avery are being picked off one by one by a ghostly apparition. They believe it to be a legendary Siren, a beautiful and mesmerizing demon who lures men to their death with its haunting Siren song. She marks her prey before retrieving them with a black spot on their hand, a mark that means certain death. As they are becalmed and stuck in the ocean, all seems lost for the dwindling pirate crew... until three stowaways are discovered with a mysterious blue crate.", sdf.parse("07-05-2011")),
                    new Episode(73, 6, 5, "The Doctor's Wife", "While traveling in the TARDIS with Rory and Amy, the Doctor hears a knock on the TARDIS doors. Bewildered and no doubt curious, he answers, only to be presented with a mysterious box which carries a distress signal. Believing it to be from a fellow Time Lord, the cosmic nomad whisks himself and his companions outside the boundaries of the universe on what should be a rescue mission. But what everyone finds is a dark Junk-yard planet populated by the bizarre Auntie, Uncle and Nephew. Last and not least among the strange inhabitants is a mentally unstable woman that ...", sdf.parse("14-05-2011")),
                    new Episode(74, 6, 6, "The Rebel Flesh", "The Doctor, Amy and Rory arrive in a future Earth where a small group of humans operate a plant extracting highly dangerous chemicals. To minimize the danger to themselves, they create clones made of a plastic-like substance, 'gangers' (short for doppelganger) who do the actual work. While forming their clones however, the Earth is struck by massive solar flare activity that transfer the humans' emotions and memories in addition to their technical abilities. As they all try to deal with what has happened, the gangers are clearly no longer prepared to accept the ...", sdf.parse("21-05-2011")),
                    new Episode(75, 6, 7, "The Almost People", "As the dopplegangers - 'gangers' for short - fight their makers, both Doctors, the real one and his ganger, try to find a way to restore the power and get everyone off the island. Both Doctors claim to be the 100% real thing, something Emily can't quite grasp. Rory meanwhile is trying to find Jennie but when he locates her and her ganger, he can't tell them apart. Having selected one of them, they discover of a company secret forces their hand. He soon realizes he's made an error. There is another ganger in the group however.", sdf.parse("28-05-2011")),
                    new Episode(76, 6, 8, "A Good Man Goes to War", "A member of The Doctor's team has been abducted and he will call in every favor and maybe even go to war to get him/her back.", sdf.parse("04-06-2011")),
                    new Episode(77, 6, 9, "Let's Kill Hitler", "In the desperate search for Melody Pond, the TARDIS crash lands in Thirties Berlin, as the time-travelling drama returns for the second half of the series shown earlier in the year. The Doctor comes face to face with the greatest war criminal in the Universe. And Hitler. Old friendships are tested to their limits as the Doctor suffers the ultimate betrayal and learns a harsh lesson in the cruelest warfare of all. As precious time ebbs away, the Doctor must teach his adversaries that time travel has responsibilities. And he must succeed before an almighty price is paid.", sdf.parse("27-08-2011")),
                    new Episode(78, 6, 10, "Night Terrors", "A young boy living in a tower block on a council estate sends out, unknowingly, a psychic distress call transmitted to the Doctor's 'psychic paper'. When the doctor and his associates eventually find the correct flat in the tower block, they are inadvertently sent by the boy into a doll house, where they are terrorized by life-size peg dolls, and are threatened with becoming peg dolls themselves.", sdf.parse("03-09-2011")),
                    new Episode(79, 6, 11, "The Girl Who Waited", "When Rory gets into the quarantine facility he faces Amy once again, but he faces her 36 years into her future. Old Amy is mad at the doctor for making her wait yet again and refuses to save her past self. She selfishly asks Rory to take her with him instead of the younger Amy, but he couldn't do that. In the end Rory gets young Amy into the TARDIS with the doctor with old Amy facing the robots outside. The doctor won't let her in and she is killed by kindness as Rory, the doctor and young Amy fly away in the TARDIS to begin another adventure somewhere else.", sdf.parse("10-09-2011")),
                    new Episode(80, 6, 12, "The God Complex", "The Doctor, Amy and Rory become trapped in a hotel of horrors unable to escape and unable to find the tardis. The Doctor must save as many people as he can taking many twists and seeing his own worst fear.", sdf.parse("17-09-2011")),
                    new Episode(81, 6, 13, "Closing Time", "After traveling for 200 years and leaving messages for Amy Pond across time and space, the Doctor realizes his time is up, its time to settle down and accept his future at Lake Silencio. . . . . .But not before one last goodbye. The Doctor travels to England and visits Craig and Sophie, who are now happily married and struggling with parenthood. Not everything is well, as the Doctor soon finds himself miraculously working at a shop and battling Cybermen.", sdf.parse("24-09-2011")),
                    new Episode(82, 6, 14, "The Wedding of River Song", "It's April 22, 2011 the day the Doctor is supposed to die but time seems to be stuck at 5:02 p.m. London streets are clogged not only with automobiles but also Roman chariots; pterodactyls fly in the sky. The Holy Roman Emperor, Winston Churchill, calls on a prisoner to explain what is happening. In fact, all time seems to be occurring all at once. The Doctor determines that a fixed point in time has been altered or prevented from occurring. That fixed point is his own death at Lake Silencio where history records that River Song killed him. Of course not all is as it ...", sdf.parse("01-10-2011")),
                    //season 7
                    new Episode(83, 7, 1, "The Doctor, the Widow and the Wardrobe", "It's Christmas Eve, 1938, when Madge Arwell comes to the aid of an injured Spaceman Angel as she cycles home. He promises to repay her kindness - all she has to do is make a wish. Three years later, a devastated Madge escapes war-torn London with her two children for a dilapidated house in Dorset. She is crippled with grief at the news her husband has been lost over the channel, but determined to give Lily and Cyril the best Christmas ever. The Arwells are surprised to be greeted by a madcap caretaker whose mysterious Christmas gift leads them into a magical wintry ...", sdf.parse("25-12-2011")),
                    new Episode(84, 7, 2, "Asylum of the Daleks", "The Doctor along with an Amy and Rory who are headed for divorce are kidnapped by the Daleks. They find themselves before the Dalek Parliament and the Doctor is quite surprised when he learns why: they want the him to save them. A ship has crashed on the one place they will not go - the Asylum, where mad Daleks are sent to spend their days. Once there, they are assisted by the only survivor of the crash, Oswin, who has been there for a year awaiting rescue and making soufflé's to pass the time. Which leads the Doctor to ask the most important question of all: where ...", sdf.parse("01-09-2012")),
                    new Episode(85, 7, 3, "Dinosaurs on a Spaceship", "After a lengthy absence, the Doctor returns to Earth and scoops up up Amy and Rory for yet another adventure. He also manages somehow to include Rory's dad, Brian Williams. Those aren't the only travelers however as Queen Nefertiti and big-game hunter John Riddell are also on board. The TARDIS next reappears on board a large ship and the Doctor is delighted to find a cargo of prehistoric dinosaurs on board. Using the ship's computers, Amy determines that the ship's crew is nowhere to be found. There is someone on board however who has no intention of giving up his ...", sdf.parse("08-09-2012")),
                    new Episode(86, 7, 4, "A Town Called Mercy", "The Doctor, Amy and Rory find themselves in the American wild west sometime in the 19th century. The small town has a Marshal but they're not that keen on the new arrivals. They are also under threat from an alien, a half-man half-robot hunter who is out to eliminate the Doctor. Not the we know but another, Kahler Jex, who has escaped from his world. He's done many good things for the local community but his past is somewhat questionable. When the Marshall is killed, it's left to the Doctor to decide how best to proceed.", sdf.parse("15-09-2012")),
                    new Episode(87, 7, 5, "The Power of Three", "Earth is suddenly visited by millions of small black cubes of unknown origin. The Doctor joins Amy, Rory and Rory's father, Brian, to help discover what these cubes bring for humanity.", sdf.parse("22-09-2012")),
                    new Episode(88, 7, 6, "The Angels Take Manhattan", "The Doctor takes Amy and Rory to New York, where the Weeping Angels are waiting for them. River Song returns.", sdf.parse("29-09-2012")),
                    new Episode(89, 7, 7, "The Snowmen", "London, 1892. Snow is trying to evolve, feeding off of the nightmares of a little girl. But the Doctor has given up on saving the world. It is up to a young governess named Clara to convince him, with just one word, to save the day.", sdf.parse("25-12-2012")),
                    new Episode(90, 7, 8, "The Bells of Saint John", "A chance phone call reunites the Doctor with Clara in the present day. A mysterious organization, lead by the evil Miss Kizlet, sends robots known as \"Spoonheads\" to steal the minds of people who use the company's WiFi. The Doctor and Clara must work together to find the location of the organization and destroy it before the whole world is trapped by the WiFi.", sdf.parse("30-03-2013")),
                    new Episode(91, 7, 9, "The Rings of Akhaten", "Still not quite able to explain just who she is, the Doctor and Clara set off on their first adventure. He takes her to see the Rings of Akhaten and its famous pyramid. The residents of the 7 planets rotating the same sun all believe the pyramid is the source of all life in the universe. There are quite a few visitors there for the Festival of Offering and Clara and helps a young girl, Merry, to have the confidence to perform an important ceremony to sooth and keep the Old God asleep. When Merry is drawn into the pyramid the Doctor and Clara go after her. When the Old...", sdf.parse("06-04-2013")),
                    new Episode(92, 7, 10, "Cold War", "The Doctor and Clara find themselves dealing with Cold War tensions when the TARDIS lands aboard a disabled Soviet ballistic submarine. The Doctor isn't the only alien being on board however - while engaged in undersea drilling, Professor Grisenko thought he'd found a mammoth and brought the creature on the boat encased in ice. It isn't a mammoth but an Ice Warrior, who has been lying dormant for 5000 years. He identifies himself as Grand Marshal Skaldak but when he cannot contact others of his kind, he assumes he is the last of his race. He now has every intention of...", sdf.parse("13-04-2013")),
                    new Episode(93, 7, 11, "Hide", "The Doctor and Clara arrive at an old manor house in 1974 where Alec Palmer and Emma Grayling are investigating the existence of a ghost. Alec is a former army Major and now a psychologist while Emma is an empathic psychic who can not only sense the presence of paranormal beings but can sense their feelings as well. Palmer explains that the house has been haunted for hundreds of years and the ghost, a woman, is likely much older. Emma senses that the ghost is very lonely but the Doctor realizes that she is not a ghost at all but a creature trapped in a zone where time...", sdf.parse("20-04-2013")),
                    new Episode(94, 7, 12, "Journey to the Centre of the TARDIS", "The Doctor and Clara find themselves aboard a space freighter that has taken the TARDIS on-board as salvage. While the Doctor is ejected, Clara finds herself wandering through the vehicle exploring it's many - seemingly infinite - rooms. The Doctor re-enters the TARDIS accompanied by three workers from the salvage ship and they have but 30 minutes to find her. There are creatures in the depths of the TARDIS and the time travel machine will do whatever it takes to protect itself. There is a rupture in time however and the TARDIS is leaking recent history....which the ...", sdf.parse("27-04-2013")),
                    new Episode(95, 7, 13, "The Crimson Horror", "The Doctor and Clara arrive in 19th century Yorkshire where moral crusader Mrs Gillyflower is recruiting beautiful people for her idyllic garden city. At the same time rigid corpses dyed red are piling up and the brother of one of the victims seeks help from Madame Vastra. She and her party travel to Yorkshire where they rescue Doctor Who and Clara from the clutches of Mrs Gillyflower. They discover that the woman is a fanatical exponent of ethnic cleansing who plans to do away with those who do not meet her standards - even her daughter Ada. The Doctor and his allies...", sdf.parse("04-05-2013")),
                    new Episode(96, 7, 14, "Nightmare in Silver", "Hedgewick's World of Wonders was once the greatest theme park in the galaxy, but it's now the dilapidated home to a shabby showman, a chess playing dwarf and a dysfunctional army platoon. When the Doctor, Clara, Artie and Angie arrive, the last thing they expect is the re-emergence of one of the Doctor's oldest foes. The Cybermen are back!", sdf.parse("11-05-2013")),
                    new Episode(97, 7, 15, "The Name of the Doctor", "The Doctor's friends are being kidnapped, which leads him to the fields of Trenzalore, where his greatest secret will be revealed and Clara's mystery will be solved.", sdf.parse("18-05-2013")),

            };
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    @Provides
    EpisodeArrayAdapter provideEpisodeArrayAdapter() {
        return new EpisodeArrayAdapter(context, resource, Arrays.asList(episodes));
    }

    ;
}